### ISSUE TITLE
Krypto methode 

### ISSUE THREAD

**Issue by henrikse55** [NaiPox/JavaProjects#1]
You set the parameter KryptoKode that's it, you don't get any return data.

Program math is like normal math. You Multiply first then add. 
`KryptoKode = Math.random()*100+1*KryptoMod;` You literally multiply a random number by 100 and `KryptoKode` with one before adding them together.
A way you Can fix this would be `KryptoKode = (Math.random()*100+1) * KryptoMod`

and Random.nextInt(n) is more effecient http://stackoverflow.com/questions/738629/math-random-versus-random-nextintint

--Edit--
And parameters is not used for returning data, (assuming that is what you are trying to do with the `string uddata`)

**Comment by NaiPox** [comment]
This is an unfinished project. Guess you got bored and started looking at stuff.
